version: 2
updates:
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "npm"
    directory: "/assets"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "npm"
    directory: "/tracker"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"