# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://gitlab.com/jvenom/elixir-pre-commit-hooks
    rev: v1.0.0
    hooks:
      - id: mix-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
        exclude: priv/tracker/js
      - id: mixed-line-ending
      - id: trailing-whitespace
